Watching for file changes with StatReloader
<div>
    <label for="id_name">Name:</label>



<input type="text" name="name" value="testadf" required id="id_name">
    
</div>

  <div>
    <label for="id_price">Price:</label>



<input type="number" name="price" value="9" step="any" required id="id_price">
    
</div>

  <div>
    <label for="id_category">Category:</label>



<input type="text" name="category" value="cat1" required id="id_category">
    
</div>

  <div>
    <label for="id_buyer_address">Buyer address:</label>



<input type="text" name="buyer_address" value="e, e, e 8888" required id="id_buyer_address">
    
      
    
</div>
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 68, in page2
    p = Product(name=product_form.cleaned_data['name'], price=product_form.cleaned_data['price'], category=product_form.cleaned_data['category'], owner=request.user, buyer_address=product_form.cleaned_data['buyer_address'], is_bought=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 287, in __set__
    raise ValueError(
ValueError: Cannot assign "'e, e, e 8888'": "Product.buyer_address" must be a "Address" instance.
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
<QuerySet []>
<QuerySet []>
<div>
    <label for="id_name">Name:</label>



<input type="text" name="name" value="testasdf" required id="id_name">
    
</div>

  <div>
    <label for="id_price">Price:</label>



<input type="number" name="price" value="4" step="any" required id="id_price">
    
</div>

  <div>
    <label for="id_category">Category:</label>



<input type="text" name="category" value="cat1" required id="id_category">
    
</div>

  <div>
    <label for="id_buyer_address">Buyer address:</label>



<input type="text" name="buyer_address" value="e, e, e 8888" required id="id_buyer_address">
    
      
    
</div>
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 70, in page2
    line1 = product_form['buyer_address'].split(',')[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BoundField' object has no attribute 'split'
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
<div>
    <label for="id_name">Name:</label>



<input type="text" name="name" value="testasdf" required id="id_name">
    
</div>

  <div>
    <label for="id_price">Price:</label>



<input type="number" name="price" value="4" step="any" required id="id_price">
    
</div>

  <div>
    <label for="id_category">Category:</label>



<input type="text" name="category" value="cat1" required id="id_category">
    
</div>

  <div>
    <label for="id_buyer_address">Buyer address:</label>



<input type="text" name="buyer_address" value="e, e, e 8888" required id="id_buyer_address">
    
      
    
</div>
<QuerySet [<Product: testasdf>]>
Internal Server Error: /
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 59, in home
    return render(request, 'site_app/index.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'buy_product' not found. 'buy_product' is not a valid view function or pattern name.
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 60, in home
    return render(request, 'site_app/index.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'buy_product' not found. 'buy_product' is not a valid view function or pattern name.
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 61, in home
    return render(request, 'site_app/index.html', {'products': product_list})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'buy_product' not found. 'buy_product' is not a valid view function or pattern name.
<div>
    <label for="id_name">Name:</label>



<input type="text" name="name" value="rob&#x27;s test product" required id="id_name">
    
</div>

  <div>
    <label for="id_price">Price:</label>



<input type="number" name="price" value="4" step="any" required id="id_price">
    
</div>

  <div>
    <label for="id_category">Category:</label>



<input type="text" name="category" value="test category" required id="id_category">
    
</div>

  <div>
    <label for="id_buyer_address">Buyer address:</label>



<input type="text" name="buyer_address" value="aa, ss, ss 88888" required id="id_buyer_address">
    
      
    
</div>
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\nikki\OneDrive\Desktop\Programming\Git\Trading\CSCI4830-TradingTreasure\trading_treasure\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /home/
C:\Users\nikki\OneDrive\Desktop\Programming\Git\Trading\CSCI4830-TradingTreasure\site_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\nikki\OneDrive\Desktop\Programming\Git\Trading\CSCI4830-TradingTreasure\site_app\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /signup
Forbidden (CSRF token from POST incorrect.): /signup
C:\Users\nikki\OneDrive\Desktop\Programming\Git\Trading\CSCI4830-TradingTreasure\site_app\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /signup
C:\Users\nikki\OneDrive\Desktop\Programming\Git\Trading\CSCI4830-TradingTreasure\site_app\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /signup
C:\Users\nikki\OneDrive\Desktop\Programming\Git\Trading\CSCI4830-TradingTreasure\site_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 81, in page2
    addr = Address.objects.get(address_line1=line1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
site_app.models.Address.MultipleObjectsReturned: get() returned more than one Address -- it returned 2!
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 81, in page2
    addr = Address.objects.get(address_line1=line1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
site_app.models.Address.MultipleObjectsReturned: get() returned more than one Address -- it returned 2!
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /update_address
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 53, in update_address
    return render(request, 'site_app/page2.html', {'profile': u, 'form': addr_form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: site_app/page2.html
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token missing.): /update_address
Forbidden (CSRF token missing.): /update_address
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 82, in page2
    addr = Address.objects.get(address_line1=line1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
site_app.models.Address.MultipleObjectsReturned: get() returned more than one Address -- it returned 2!
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 82, in page2
    addr = Address.objects.get(address_line1=line1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
site_app.models.Address.MultipleObjectsReturned: get() returned more than one Address -- it returned 2!
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 82, in page2
    addr = Address.objects.get(address_line1=line1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
site_app.models.Address.MultipleObjectsReturned: get() returned more than one Address -- it returned 2!
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 82, in page2
    addr = Address.objects.get(address_line1=line1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
site_app.models.Address.MultipleObjectsReturned: get() returned more than one Address -- it returned 2!
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 82, in page2
    addr = Address.objects.get(address_line1=line1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
site_app.models.Address.MultipleObjectsReturned: get() returned more than one Address -- it returned 2!
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /page2/
Traceback (most recent call last):
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/site_app/views.py", line 83, in page2
    addr = Address.objects.get(address_line1=line1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gareth/school/software_eng/group-project/env/lib/python3.12/site-packages/django/db/models/query.py", line 652, in get
    raise self.model.MultipleObjectsReturned(
site_app.models.Address.MultipleObjectsReturned: get() returned more than one Address -- it returned 2!
/home/gareth/school/software_eng/group-project/site_app/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /buy-item/6581153e-cdfe-408d-92ad-153fc42032f0/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\site_app\views.py", line 107, in buy_item
    form = StripePaymentForm(initial={'product_id': prod.id})
           ^^^^^^^^^^^^^^^^^
NameError: name 'StripePaymentForm' is not defined
Internal Server Error: /buy-item/bfe410fb-b7c9-4b54-9afc-0d5e73bd0bf5/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\site_app\views.py", line 107, in buy_item
    form = StripePaymentForm(initial={'product_id': prod.id})
           ^^^^^^^^^^^^^^^^^
NameError: name 'StripePaymentForm' is not defined
Watching for file changes with StatReloader
Internal Server Error: /buy-item/6581153e-cdfe-408d-92ad-153fc42032f0/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\site_app\views.py", line 108, in buy_item
    form = StripePaymentForm(initial={'product_id': prod.id})
           ^^^^^^^^^^^^^^^^^
NameError: name 'StripePaymentForm' is not defined
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
message='Request to Stripe api' method=post url=https://api.stripe.com/v1/checkout/sessions
api_version=2025-04-30.basil message='Post details' post_data=payment_method_types[0]=card&line_items[0][price_data][currency]=usd&line_items[0][price_data][product_data][name]=asdf&line_items[0][price_data][unit_amount]=300&line_items[0][quantity]=1&mode=payment&success_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_success%2F&cancel_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_cancel%2F
Starting new HTTPS connection (1): api.stripe.com:443
https://api.stripe.com:443 "POST /v1/checkout/sessions HTTP/1.1" 200 2592
message='Stripe API response' path=https://api.stripe.com/v1/checkout/sessions response_code=200
body='{\n  "id": "cs_test_a1QOjEw20bklRCslkq3i0qZQJ6plZQKyfQ7M39CrTomfEbz9lN2AcccS9k",\n  "object": "checkout.session",\n  "adaptive_pricing": {\n    "enabled": true\n  },\n  "after_expiration": null,\n  "allow_promotion_codes": null,\n  "amount_subtotal": 300,\n  "amount_total": 300,\n  "automatic_tax": {\n    "enabled": false,\n    "liability": null,\n    "provider": null,\n    "status": null\n  },\n  "billing_address_collection": null,\n  "cancel_url": "http://127.0.0.1:8000/pay_cancel/",\n  "client_reference_id": null,\n  "client_secret": null,\n  "collected_information": null,\n  "consent": null,\n  "consent_collection": null,\n  "created": 1746053359,\n  "currency": "usd",\n  "currency_conversion": null,\n  "custom_fields": [],\n  "custom_text": {\n    "after_submit": null,\n    "shipping_address": null,\n    "submit": null,\n    "terms_of_service_acceptance": null\n  },\n  "customer": null,\n  "customer_creation": "if_required",\n  "customer_details": null,\n  "customer_email": null,\n  "discounts": [],\n  "expires_at": 1746139759,\n  "invoice": null,\n  "invoice_creation": {\n    "enabled": false,\n    "invoice_data": {\n      "account_tax_ids": null,\n      "custom_fields": null,\n      "description": null,\n      "footer": null,\n      "issuer": null,\n      "metadata": {},\n      "rendering_options": null\n    }\n  },\n  "livemode": false,\n  "locale": null,\n  "metadata": {},\n  "mode": "payment",\n  "payment_intent": null,\n  "payment_link": null,\n  "payment_method_collection": "if_required",\n  "payment_method_configuration_details": null,\n  "payment_method_options": {\n    "card": {\n      "request_three_d_secure": "automatic"\n    }\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "payment_status": "unpaid",\n  "permissions": null,\n  "phone_number_collection": {\n    "enabled": false\n  },\n  "recovered_from": null,\n  "saved_payment_method_options": null,\n  "setup_intent": null,\n  "shipping_address_collection": null,\n  "shipping_cost": null,\n  "shipping_options": [],\n  "status": "open",\n  "submit_type": null,\n  "subscription": null,\n  "success_url": "http://127.0.0.1:8000/pay_success/",\n  "total_details": {\n    "amount_discount": 0,\n    "amount_shipping": 0,\n    "amount_tax": 0\n  },\n  "ui_mode": "hosted",\n  "url": "https://checkout.stripe.com/c/pay/cs_test_a1QOjEw20bklRCslkq3i0qZQJ6plZQKyfQ7M39CrTomfEbz9lN2AcccS9k#fidkdWxOYHwnPyd1blpxYHZxWjA0V09MczBXcjRWRmdzZ2dOMH1%2FMzY9UElrfDRTZG8yU21BUkpjYm58UktkTDBhUGZkQT1yVjBCPGZSf1ExSGdnV0xHdjRAbGlTa2RUX2F9cWRTNUdkSExVNTV2a2NAMXZcYCcpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl",\n  "wallet_options": null\n}' message='API response body'
link=https://dashboard.stripe.com/test/logs/req_PGnDQW0fGe3G4w message='Dashboard link for request'
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Watching for file changes with StatReloader
message='Request to Stripe api' method=post url=https://api.stripe.com/v1/checkout/sessions
api_version=2025-04-30.basil message='Post details' post_data=payment_method_types[0]=card&line_items[0][price_data][currency]=usd&line_items[0][price_data][product_data][name]=asdf&line_items[0][price_data][unit_amount]=300&line_items[0][quantity]=1&mode=payment&success_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_success%2F&cancel_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_cancel%2F
Starting new HTTPS connection (1): api.stripe.com:443
https://api.stripe.com:443 "POST /v1/checkout/sessions HTTP/1.1" 200 2592
message='Stripe API response' path=https://api.stripe.com/v1/checkout/sessions response_code=200
body='{\n  "id": "cs_test_a1AwKJk82JDncm3argzL9rkLOaZfT0Vwo1mLnIi3ZkBEMUGGzj6LCKMGaB",\n  "object": "checkout.session",\n  "adaptive_pricing": {\n    "enabled": true\n  },\n  "after_expiration": null,\n  "allow_promotion_codes": null,\n  "amount_subtotal": 300,\n  "amount_total": 300,\n  "automatic_tax": {\n    "enabled": false,\n    "liability": null,\n    "provider": null,\n    "status": null\n  },\n  "billing_address_collection": null,\n  "cancel_url": "http://127.0.0.1:8000/pay_cancel/",\n  "client_reference_id": null,\n  "client_secret": null,\n  "collected_information": null,\n  "consent": null,\n  "consent_collection": null,\n  "created": 1746054097,\n  "currency": "usd",\n  "currency_conversion": null,\n  "custom_fields": [],\n  "custom_text": {\n    "after_submit": null,\n    "shipping_address": null,\n    "submit": null,\n    "terms_of_service_acceptance": null\n  },\n  "customer": null,\n  "customer_creation": "if_required",\n  "customer_details": null,\n  "customer_email": null,\n  "discounts": [],\n  "expires_at": 1746140497,\n  "invoice": null,\n  "invoice_creation": {\n    "enabled": false,\n    "invoice_data": {\n      "account_tax_ids": null,\n      "custom_fields": null,\n      "description": null,\n      "footer": null,\n      "issuer": null,\n      "metadata": {},\n      "rendering_options": null\n    }\n  },\n  "livemode": false,\n  "locale": null,\n  "metadata": {},\n  "mode": "payment",\n  "payment_intent": null,\n  "payment_link": null,\n  "payment_method_collection": "if_required",\n  "payment_method_configuration_details": null,\n  "payment_method_options": {\n    "card": {\n      "request_three_d_secure": "automatic"\n    }\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "payment_status": "unpaid",\n  "permissions": null,\n  "phone_number_collection": {\n    "enabled": false\n  },\n  "recovered_from": null,\n  "saved_payment_method_options": null,\n  "setup_intent": null,\n  "shipping_address_collection": null,\n  "shipping_cost": null,\n  "shipping_options": [],\n  "status": "open",\n  "submit_type": null,\n  "subscription": null,\n  "success_url": "http://127.0.0.1:8000/pay_success/",\n  "total_details": {\n    "amount_discount": 0,\n    "amount_shipping": 0,\n    "amount_tax": 0\n  },\n  "ui_mode": "hosted",\n  "url": "https://checkout.stripe.com/c/pay/cs_test_a1AwKJk82JDncm3argzL9rkLOaZfT0Vwo1mLnIi3ZkBEMUGGzj6LCKMGaB#fidkdWxOYHwnPyd1blpxYHZxWjA0V09MczBXcjRWRmdzZ2dOMH1%2FMzY9UElrfDRTZG8yU21BUkpjYm58UktkTDBhUGZkQT1yVjBCPGZSf1ExSGdnV0xHdjRAbGlTa2RUX2F9cWRTNUdkSExVNTV2a2NAMXZcYCcpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl",\n  "wallet_options": null\n}' message='API response body'
link=https://dashboard.stripe.com/test/logs/req_L95gNS0RzBJOdM message='Dashboard link for request'
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Watching for file changes with StatReloader
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Watching for file changes with StatReloader
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
message='Request to Stripe api' method=post url=https://api.stripe.com/v1/checkout/sessions
api_version=2025-04-30.basil message='Post details' post_data=payment_method_types[0]=card&line_items[0][price_data][currency]=usd&line_items[0][price_data][product_data][name]=asdf&line_items[0][price_data][unit_amount]=300&line_items[0][quantity]=1&mode=payment&success_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_success%2F&cancel_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_cancel%2F
Starting new HTTPS connection (1): api.stripe.com:443
https://api.stripe.com:443 "POST /v1/checkout/sessions HTTP/1.1" 200 2592
message='Stripe API response' path=https://api.stripe.com/v1/checkout/sessions response_code=200
body='{\n  "id": "cs_test_a1OLJWF0rfbOQwM94FXVysdqxwqOSHkDP4gfd9cZyxuBHREToNtlnineSL",\n  "object": "checkout.session",\n  "adaptive_pricing": {\n    "enabled": true\n  },\n  "after_expiration": null,\n  "allow_promotion_codes": null,\n  "amount_subtotal": 300,\n  "amount_total": 300,\n  "automatic_tax": {\n    "enabled": false,\n    "liability": null,\n    "provider": null,\n    "status": null\n  },\n  "billing_address_collection": null,\n  "cancel_url": "http://127.0.0.1:8000/pay_cancel/",\n  "client_reference_id": null,\n  "client_secret": null,\n  "collected_information": null,\n  "consent": null,\n  "consent_collection": null,\n  "created": 1746054596,\n  "currency": "usd",\n  "currency_conversion": null,\n  "custom_fields": [],\n  "custom_text": {\n    "after_submit": null,\n    "shipping_address": null,\n    "submit": null,\n    "terms_of_service_acceptance": null\n  },\n  "customer": null,\n  "customer_creation": "if_required",\n  "customer_details": null,\n  "customer_email": null,\n  "discounts": [],\n  "expires_at": 1746140996,\n  "invoice": null,\n  "invoice_creation": {\n    "enabled": false,\n    "invoice_data": {\n      "account_tax_ids": null,\n      "custom_fields": null,\n      "description": null,\n      "footer": null,\n      "issuer": null,\n      "metadata": {},\n      "rendering_options": null\n    }\n  },\n  "livemode": false,\n  "locale": null,\n  "metadata": {},\n  "mode": "payment",\n  "payment_intent": null,\n  "payment_link": null,\n  "payment_method_collection": "if_required",\n  "payment_method_configuration_details": null,\n  "payment_method_options": {\n    "card": {\n      "request_three_d_secure": "automatic"\n    }\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "payment_status": "unpaid",\n  "permissions": null,\n  "phone_number_collection": {\n    "enabled": false\n  },\n  "recovered_from": null,\n  "saved_payment_method_options": null,\n  "setup_intent": null,\n  "shipping_address_collection": null,\n  "shipping_cost": null,\n  "shipping_options": [],\n  "status": "open",\n  "submit_type": null,\n  "subscription": null,\n  "success_url": "http://127.0.0.1:8000/pay_success/",\n  "total_details": {\n    "amount_discount": 0,\n    "amount_shipping": 0,\n    "amount_tax": 0\n  },\n  "ui_mode": "hosted",\n  "url": "https://checkout.stripe.com/c/pay/cs_test_a1OLJWF0rfbOQwM94FXVysdqxwqOSHkDP4gfd9cZyxuBHREToNtlnineSL#fidkdWxOYHwnPyd1blpxYHZxWjA0V09MczBXcjRWRmdzZ2dOMH1%2FMzY9UElrfDRTZG8yU21BUkpjYm58UktkTDBhUGZkQT1yVjBCPGZSf1ExSGdnV0xHdjRAbGlTa2RUX2F9cWRTNUdkSExVNTV2a2NAMXZcYCcpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl",\n  "wallet_options": null\n}' message='API response body'
link=https://dashboard.stripe.com/test/logs/req_PyIk4ACHeaqUzV message='Dashboard link for request'
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Watching for file changes with StatReloader
Watching for file changes with StatReloader
message='Request to Stripe api' method=post url=https://api.stripe.com/v1/checkout/sessions
api_version=2025-04-30.basil message='Post details' post_data=payment_method_types[0]=card&line_items[0][price_data][currency]=usd&line_items[0][price_data][product_data][name]=asdf&line_items[0][price_data][unit_amount]=300&line_items[0][quantity]=1&mode=payment&success_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_success%2F&cancel_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_cancel%2F
Starting new HTTPS connection (1): api.stripe.com:443
https://api.stripe.com:443 "POST /v1/checkout/sessions HTTP/1.1" 200 2592
message='Stripe API response' path=https://api.stripe.com/v1/checkout/sessions response_code=200
body='{\n  "id": "cs_test_a1K4VWnuZhPoOv65qwqSWN7r26Oo3sSmux0fgkTznx4b2jdOUb8n7wgavq",\n  "object": "checkout.session",\n  "adaptive_pricing": {\n    "enabled": true\n  },\n  "after_expiration": null,\n  "allow_promotion_codes": null,\n  "amount_subtotal": 300,\n  "amount_total": 300,\n  "automatic_tax": {\n    "enabled": false,\n    "liability": null,\n    "provider": null,\n    "status": null\n  },\n  "billing_address_collection": null,\n  "cancel_url": "http://127.0.0.1:8000/pay_cancel/",\n  "client_reference_id": null,\n  "client_secret": null,\n  "collected_information": null,\n  "consent": null,\n  "consent_collection": null,\n  "created": 1746054787,\n  "currency": "usd",\n  "currency_conversion": null,\n  "custom_fields": [],\n  "custom_text": {\n    "after_submit": null,\n    "shipping_address": null,\n    "submit": null,\n    "terms_of_service_acceptance": null\n  },\n  "customer": null,\n  "customer_creation": "if_required",\n  "customer_details": null,\n  "customer_email": null,\n  "discounts": [],\n  "expires_at": 1746141187,\n  "invoice": null,\n  "invoice_creation": {\n    "enabled": false,\n    "invoice_data": {\n      "account_tax_ids": null,\n      "custom_fields": null,\n      "description": null,\n      "footer": null,\n      "issuer": null,\n      "metadata": {},\n      "rendering_options": null\n    }\n  },\n  "livemode": false,\n  "locale": null,\n  "metadata": {},\n  "mode": "payment",\n  "payment_intent": null,\n  "payment_link": null,\n  "payment_method_collection": "if_required",\n  "payment_method_configuration_details": null,\n  "payment_method_options": {\n    "card": {\n      "request_three_d_secure": "automatic"\n    }\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "payment_status": "unpaid",\n  "permissions": null,\n  "phone_number_collection": {\n    "enabled": false\n  },\n  "recovered_from": null,\n  "saved_payment_method_options": null,\n  "setup_intent": null,\n  "shipping_address_collection": null,\n  "shipping_cost": null,\n  "shipping_options": [],\n  "status": "open",\n  "submit_type": null,\n  "subscription": null,\n  "success_url": "http://127.0.0.1:8000/pay_success/",\n  "total_details": {\n    "amount_discount": 0,\n    "amount_shipping": 0,\n    "amount_tax": 0\n  },\n  "ui_mode": "hosted",\n  "url": "https://checkout.stripe.com/c/pay/cs_test_a1K4VWnuZhPoOv65qwqSWN7r26Oo3sSmux0fgkTznx4b2jdOUb8n7wgavq#fidkdWxOYHwnPyd1blpxYHZxWjA0V09MczBXcjRWRmdzZ2dOMH1%2FMzY9UElrfDRTZG8yU21BUkpjYm58UktkTDBhUGZkQT1yVjBCPGZSf1ExSGdnV0xHdjRAbGlTa2RUX2F9cWRTNUdkSExVNTV2a2NAMXZcYCcpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl",\n  "wallet_options": null\n}' message='API response body'
link=https://dashboard.stripe.com/test/logs/req_6YNm8zhX3bBkL2 message='Dashboard link for request'
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Watching for file changes with StatReloader
message='Request to Stripe api' method=post url=https://api.stripe.com/v1/checkout/sessions
api_version=2025-04-30.basil message='Post details' post_data=payment_method_types[0]=card&line_items[0][price_data][currency]=usd&line_items[0][price_data][product_data][name]=asdf&line_items[0][price_data][unit_amount]=300&line_items[0][quantity]=1&mode=payment&success_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_success%2F&cancel_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_cancel%2F
Starting new HTTPS connection (1): api.stripe.com:443
https://api.stripe.com:443 "POST /v1/checkout/sessions HTTP/1.1" 200 2592
message='Stripe API response' path=https://api.stripe.com/v1/checkout/sessions response_code=200
body='{\n  "id": "cs_test_a1SzNYUeuCPl1qLEkUgHR9mZkm2FXOcVZg1PKREYIkJ4s80iC0GGTawNbd",\n  "object": "checkout.session",\n  "adaptive_pricing": {\n    "enabled": true\n  },\n  "after_expiration": null,\n  "allow_promotion_codes": null,\n  "amount_subtotal": 300,\n  "amount_total": 300,\n  "automatic_tax": {\n    "enabled": false,\n    "liability": null,\n    "provider": null,\n    "status": null\n  },\n  "billing_address_collection": null,\n  "cancel_url": "http://127.0.0.1:8000/pay_cancel/",\n  "client_reference_id": null,\n  "client_secret": null,\n  "collected_information": null,\n  "consent": null,\n  "consent_collection": null,\n  "created": 1746055297,\n  "currency": "usd",\n  "currency_conversion": null,\n  "custom_fields": [],\n  "custom_text": {\n    "after_submit": null,\n    "shipping_address": null,\n    "submit": null,\n    "terms_of_service_acceptance": null\n  },\n  "customer": null,\n  "customer_creation": "if_required",\n  "customer_details": null,\n  "customer_email": null,\n  "discounts": [],\n  "expires_at": 1746141697,\n  "invoice": null,\n  "invoice_creation": {\n    "enabled": false,\n    "invoice_data": {\n      "account_tax_ids": null,\n      "custom_fields": null,\n      "description": null,\n      "footer": null,\n      "issuer": null,\n      "metadata": {},\n      "rendering_options": null\n    }\n  },\n  "livemode": false,\n  "locale": null,\n  "metadata": {},\n  "mode": "payment",\n  "payment_intent": null,\n  "payment_link": null,\n  "payment_method_collection": "if_required",\n  "payment_method_configuration_details": null,\n  "payment_method_options": {\n    "card": {\n      "request_three_d_secure": "automatic"\n    }\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "payment_status": "unpaid",\n  "permissions": null,\n  "phone_number_collection": {\n    "enabled": false\n  },\n  "recovered_from": null,\n  "saved_payment_method_options": null,\n  "setup_intent": null,\n  "shipping_address_collection": null,\n  "shipping_cost": null,\n  "shipping_options": [],\n  "status": "open",\n  "submit_type": null,\n  "subscription": null,\n  "success_url": "http://127.0.0.1:8000/pay_success/",\n  "total_details": {\n    "amount_discount": 0,\n    "amount_shipping": 0,\n    "amount_tax": 0\n  },\n  "ui_mode": "hosted",\n  "url": "https://checkout.stripe.com/c/pay/cs_test_a1SzNYUeuCPl1qLEkUgHR9mZkm2FXOcVZg1PKREYIkJ4s80iC0GGTawNbd#fidkdWxOYHwnPyd1blpxYHZxWjA0V09MczBXcjRWRmdzZ2dOMH1%2FMzY9UElrfDRTZG8yU21BUkpjYm58UktkTDBhUGZkQT1yVjBCPGZSf1ExSGdnV0xHdjRAbGlTa2RUX2F9cWRTNUdkSExVNTV2a2NAMXZcYCcpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl",\n  "wallet_options": null\n}' message='API response body'
link=https://dashboard.stripe.com/test/logs/req_Xadii8rq1AHTkV message='Dashboard link for request'
Internal Server Error: /pay_success/
Traceback (most recent call last):
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bmlm1\School Shit\Intro to Software Engineering\CSCI4830-TradingTreasure-Stripe\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: payment_success.html
Watching for file changes with StatReloader
message='Request to Stripe api' method=post url=https://api.stripe.com/v1/checkout/sessions
api_version=2025-04-30.basil message='Post details' post_data=payment_method_types[0]=card&line_items[0][price_data][currency]=usd&line_items[0][price_data][product_data][name]=asdf&line_items[0][price_data][unit_amount]=300&line_items[0][quantity]=1&mode=payment&success_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_success%2F&cancel_url=http%3A%2F%2F127.0.0.1%3A8000%2Fpay_cancel%2F
Starting new HTTPS connection (1): api.stripe.com:443
https://api.stripe.com:443 "POST /v1/checkout/sessions HTTP/1.1" 200 2592
message='Stripe API response' path=https://api.stripe.com/v1/checkout/sessions response_code=200
body='{\n  "id": "cs_test_a1MtDgpOjWWCQCgKqyf1pa6jxHOSeeBghtHBc5PB1Cqt34axsdwbcx8ri0",\n  "object": "checkout.session",\n  "adaptive_pricing": {\n    "enabled": true\n  },\n  "after_expiration": null,\n  "allow_promotion_codes": null,\n  "amount_subtotal": 300,\n  "amount_total": 300,\n  "automatic_tax": {\n    "enabled": false,\n    "liability": null,\n    "provider": null,\n    "status": null\n  },\n  "billing_address_collection": null,\n  "cancel_url": "http://127.0.0.1:8000/pay_cancel/",\n  "client_reference_id": null,\n  "client_secret": null,\n  "collected_information": null,\n  "consent": null,\n  "consent_collection": null,\n  "created": 1746055860,\n  "currency": "usd",\n  "currency_conversion": null,\n  "custom_fields": [],\n  "custom_text": {\n    "after_submit": null,\n    "shipping_address": null,\n    "submit": null,\n    "terms_of_service_acceptance": null\n  },\n  "customer": null,\n  "customer_creation": "if_required",\n  "customer_details": null,\n  "customer_email": null,\n  "discounts": [],\n  "expires_at": 1746142260,\n  "invoice": null,\n  "invoice_creation": {\n    "enabled": false,\n    "invoice_data": {\n      "account_tax_ids": null,\n      "custom_fields": null,\n      "description": null,\n      "footer": null,\n      "issuer": null,\n      "metadata": {},\n      "rendering_options": null\n    }\n  },\n  "livemode": false,\n  "locale": null,\n  "metadata": {},\n  "mode": "payment",\n  "payment_intent": null,\n  "payment_link": null,\n  "payment_method_collection": "if_required",\n  "payment_method_configuration_details": null,\n  "payment_method_options": {\n    "card": {\n      "request_three_d_secure": "automatic"\n    }\n  },\n  "payment_method_types": [\n    "card"\n  ],\n  "payment_status": "unpaid",\n  "permissions": null,\n  "phone_number_collection": {\n    "enabled": false\n  },\n  "recovered_from": null,\n  "saved_payment_method_options": null,\n  "setup_intent": null,\n  "shipping_address_collection": null,\n  "shipping_cost": null,\n  "shipping_options": [],\n  "status": "open",\n  "submit_type": null,\n  "subscription": null,\n  "success_url": "http://127.0.0.1:8000/pay_success/",\n  "total_details": {\n    "amount_discount": 0,\n    "amount_shipping": 0,\n    "amount_tax": 0\n  },\n  "ui_mode": "hosted",\n  "url": "https://checkout.stripe.com/c/pay/cs_test_a1MtDgpOjWWCQCgKqyf1pa6jxHOSeeBghtHBc5PB1Cqt34axsdwbcx8ri0#fidkdWxOYHwnPyd1blpxYHZxWjA0V09MczBXcjRWRmdzZ2dOMH1%2FMzY9UElrfDRTZG8yU21BUkpjYm58UktkTDBhUGZkQT1yVjBCPGZSf1ExSGdnV0xHdjRAbGlTa2RUX2F9cWRTNUdkSExVNTV2a2NAMXZcYCcpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl",\n  "wallet_options": null\n}' message='API response body'
link=https://dashboard.stripe.com/test/logs/req_1dxcQGEYWoRFOl message='Dashboard link for request'
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /static/assets/css/font-awesome.min.css
Watching for file changes with StatReloader
Not Found: /static/assets/css/font-awesome.min.css
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /page3/
Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: site_app_order.stripe_session_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py", line 126, in page3
    return render(request, 'site_app/elements.html', {'orders': account_orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: site_app_order.stripe_session_id
Watching for file changes with StatReloader
Internal Server Error: /page3/
Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: site_app_order.stripe_session_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py", line 126, in page3
    return render(request, 'site_app/elements.html', {'orders': account_orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: site_app_order.stripe_session_id
C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\trading_treasure\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /page3/
Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: site_app_order.stripe_session_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py", line 126, in page3
    return render(request, 'site_app/elements.html', {'orders': account_orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: site_app_order.stripe_session_id
Watching for file changes with StatReloader
Internal Server Error: /page3/
Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: site_app_order.stripe_session_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py", line 126, in page3
    return render(request, 'site_app/elements.html', {'orders': account_orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: site_app_order.stripe_session_id
Watching for file changes with StatReloader
C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\trading_treasure\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/cat1.jpg
Not Found: /static/images/ProductImages/test category.jpg
Not Found: /static/images/ProductImages/dfff.jpg
Not Found: /static/images/ProductImages/cat1.jpg
Not Found: /static/images/ProductImages/test category.jpg
Not Found: /static/images/ProductImages/placeholder.jpg
Not Found: /static/images/ProductImages/dfff.jpg
Not Found: /static/images/ProductImages/cat1.jpg
Not Found: /static/images/ProductImages/test category.jpg
Not Found: /static/images/ProductImages/dfff.jpg
Not Found: /static/images/ProductImages/placeholder.jpg
Not Found: /static/images/Productimages/cat1.jpg
Not Found: /static/images/Productimages/test category.jpg
Not Found: /static/images/Productimages/dfff.jpg
Not Found: /static/images/Productimages/placeholder.jpg
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/cat1.jpg
Not Found: /static/images/ProductImages/test category.jpg
Not Found: /static/images/ProductImages/dfff.jpg
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/cat1.jpg
Not Found: /static/images/ProductImages/test category.jpg
Not Found: /static/images/ProductImages/dfff.jpg
Watching for file changes with StatReloader
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
Watching for file changes with StatReloader
C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py changed, reloading.
Watching for file changes with StatReloader
=======
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/ProductImages/placeholder.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/notACatergory.jpg
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /static/images/ProductImages/placeholder.jpg
Not Found: /static/images/ProductImages/notACatergory.jpg
Not Found: /static/images/ProductImages/wobbles.jpg
Not Found: /static/images/ProductImages/wobbles.jpg
Internal Server Error: /pay/
Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py", line 216, in post
    checkout_session = stripe.checkout.Session.create(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\checkout\_session.py", line 4918, in create
    cls._static_request(
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\_api_resource.py", line 172, in _static_request
    return _APIRequestor._global_instance().request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\_api_requestor.py", line 187, in request
    rbody, rcode, rheaders = requestor.request_raw(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\_api_requestor.py", line 686, in request_raw
    ) = self._args_for_request_with_retries(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\_api_requestor.py", line 546, in _args_for_request_with_retries
    raise error.AuthenticationError(
stripe._error.AuthenticationError: No API key provided. (HINT: set your API key using "stripe.api_key = <API-KEY>"). You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.
C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\trading_treasure\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /pay/
Traceback (most recent call last):
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Documents\GitHub\CSCI4830-TradingTreasure\site_app\views.py", line 216, in post
    checkout_session = stripe.checkout.Session.create(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\checkout\_session.py", line 4918, in create
    cls._static_request(
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\_api_resource.py", line 172, in _static_request
    return _APIRequestor._global_instance().request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\_api_requestor.py", line 187, in request
    rbody, rcode, rheaders = requestor.request_raw(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\_api_requestor.py", line 686, in request_raw
    ) = self._args_for_request_with_retries(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jwilb\Desktop\my Python Projects\Software Development Projects\TT2\.venv\Lib\site-packages\stripe\_api_requestor.py", line 546, in _args_for_request_with_retries
    raise error.AuthenticationError(
stripe._error.AuthenticationError: No API key provided. (HINT: set your API key using "stripe.api_key = <API-KEY>"). You can generate API keys from the Stripe web interface.  See https://stripe.com/api for details, or email support@stripe.com if you have any questions.
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
